board_game:
  name: gomoku
  m: 15
  n: 15
  k: 5
  cell_size: 30
  fps: 5
  menu_font_size: 30
  button_font_size: 25
  symbol_font_size: 30
bot:
  algorithm: mcts
  config:
    max_thinking_time: 5.0  # in seconds
    max_rollout: 1000000000
    processes: 8  # number of processes
    policy: simple 
    exploration_const: 1.4142135623730951
